project_id: de4py

base_path: .

preserve_hierarchy: true

placeholders:
  - '{count}'
  - '{name}'

ignore:
  - '**/*.py'

github:
  auto_push: 1
  branch_mapping:
    main: main
  commit_message: Update translations from Crowdin

files:
  - source: /de4py/lang/locales/en.json
    translation: /de4py/lang/locales/%two_letters_code%.json
    type: json
    update_option: update_as_unapproved
    languages_mapping:
      zh-CN: zh-cn
      zh-TW: zh-tw
