project_id: de4py
placeholders:
  - '{count}'
  - '{name}'
ignore:
  - '**/*.py'
github:
  auto_push: 1
  branch_mapping:
    main: main
  commit_message: Update translations from Crowdin
base_path: .
files:
  - source: de4py/lang/locales/en.json
    translation: de4py/lang/locales/%locale%.json
    type: json
    update_option: update_as_unapproved
